### ISSUE TITLE
[Request] Feature Suggestions and Bug Discovery

### ISSUE THREAD

**Issue by nyangko** [exyte/Chat#25]
I have been using the source code you created, and it's very well. Below, I have detailed what I've noticed while working with it.

PS: I translated this because I'm not proficient in English. If there are any parts you don't understand, please answer.

**Working Environment:**

- **XCode**: Version 14.3.1 (14E300c)
- **Swift**: Version 5
- **iOS**: 15.0 or higher

**Feature Suggestions:**

**1. Add Menu on Message's Long Press Gesture:**
  - Copy message
  - Edit message
  - Delete message
  - Forward
  - Message's Long Press Gesture:

**2. Add shadow to message Bubble**

**3. Detailed View of Image Messages:**
  - download image
  - Copy image

**4. Voice Message Recording:**
    - Provide voice spectrum instead of displaying "Recording..."
    ex) https://volpato.dev/posts/speech-wave-visualization-in-swiftui/

**5. When New Messages Arrive (with isScrolledToBottom = true):**
    - Display the number of new messages as a badge

**6. Add Style to Buttons:**
    - Use .buttonStyle(.plain)
    
**7. Add a Closure for Handling Message Display Animations**

**8. Feature to Change the Profile in the Message Window When the User Profile Changes**

**Things Suspected to be Bugs:**

- Sometimes, the layout overlaps when displaying messages.
- The chat scroll animation operates abnormally, causing a shaking problem.
- The scroll animation behaves unpredictably when there are only a few messages (about 1-3).

**Comment by f3dm76** [comment]
Hey @nyangko, thank you for your kind words and suggestions. Most of these features are part of our future plan for this library, however we don't have resources right now to implement these. 

2 - You can pass custom message builder to have any design you want
6 - If I remember correctly all the buttons are customisable too.please provide screenshots if you are having problems
7 and 8 I'm not sure I understand sorry
7 - You mean appearing from the bottom of the table animation? you want to change it? but this one is the only one which makes sense
8 - If you need to update displayed information, that is solved on your end, because you are the one providing the content in the first place. Make something @publishable I guess.

About the bugs, could you please create separate issues for each, provide full minimal compilable examples and make sure the issues reproduce on them, so I can fix. Have a wonderful day

**Comment by nyangko** [comment]
Thank you for your reply. It's unfortunate that the resources are lacking.

7. I was referring to the animation effect when a message is added. In the relevant code, it is seen as `tableView.insertRows(at: [IndexPath(row: offset, section: index)], with: .top)` in UIList.swift. I thought it would be nice if there were a function that provided different animations.

8. I understand what you mean. Thank you so much.

I will organize and post about the bugs later. 
I want to express my sincere thanks for your kind response.
