### ISSUE TITLE
How can we add custom message type?

### ISSUE THREAD

**Issue by deanthing** [exyte/Chat#80]
I want to support custom message types. For example, I have documents that I want to send as a message when they are created. The message should contain information such as: title, blurb, documentId. How can I store this inside of a `Message`?

I would also want to provide custom styling, which I can assume can be done through `messageBuilder`. I am wondering how we can structure the `Message` so that we can switch on it inside the `messageBuilder` and display accordingly. 

I want to keep all the displays of the standard messages the same other than my custom message type.

Any advice is greatly appreciated!

**Comment by f3dm76** [comment]
There is no splitting into message types, since all the types can be mixed - e.g. a message with images, text and a document - what type will that be? I can add a customInfo [String: Any] dictionary to the Message, but I think strongly typed solutions are better. So this is how I do it usually:

struct BEMessage {
// vars from ExyteChat.Message
var documentId: String?
}

// your ViewModel
var libMessages: [ExyteChat.Message] {
get {
yourBEMessages.map{$0.toLibMessage()}
}
}

var yourBEMessages: [BEMessage] = ...

// your ChatView view, using messageBuilder, correct
func messageView(message: ExyteChat.Message) {
if let get yourMessage = viewModel.yourBEMessages[message.id] {
//display your document and other message details
}
}

If you want to use built-in message styling exactly as it is, please just copy this view from the source code and modify accordingly to add the document support

**Comment by deanthing** [comment]
Perfect, thanks for your help!

**Comment by Deniffer001** [comment]
@f3dm76 hello developer, i do appreciate the hard work your guys did. today  i am facing the same issue, i want to let messageView more customize, e.g.  (show some options button in messageView), and the messageView will someHow need some field to decide which to show , So what i need is to add some additional field to Message structure.

**Comment by f3dm76** [comment]
Hey @Deniffer001, thank you for your kind words, I think I can add smth like `payload: [String: Any]` to message model. Would that be a good solution, what do you think? You can store additional info on your side grabbing all extra info by message's id, but I understand it's not super convenient. Untyped payload is not perfect either, but still. Please let me know what you think, have a good day!
